-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 15:49:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ObjectType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ObjectType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ObjectType` (
  `ObjectType_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ObjectType_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ObjectType_ID_UNIQUE` ON `mydb`.`ObjectType` (`ObjectType_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Object` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Object` (
  `Object_ID` INT NOT NULL AUTO_INCREMENT,
  `ObjectType_ID` INT NOT NULL,
  `CreationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletionDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `IsDeleted` BINARY NULL DEFAULT 0,
  PRIMARY KEY (`Object_ID`),
  CONSTRAINT `fk_Object_ObjectType`
    FOREIGN KEY (`ObjectType_ID`)
    REFERENCES `mydb`.`ObjectType` (`ObjectType_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Object_ObjectType_idx` ON `mydb`.`Object` (`ObjectType_ID` ASC);

CREATE UNIQUE INDEX `Object_ID_UNIQUE` ON `mydb`.`Object` (`Object_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `CreationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletionDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Is_Deleted` BINARY NOT NULL DEFAULT 0,
  `Is_Admin` BINARY NOT NULL,
  `HumanName` VARCHAR(255) NULL,
  `Username` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `User_ID_UNIQUE` ON `mydb`.`User` (`User_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Commentary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commentary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commentary` (
  `Commentary_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Object_ID` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Content` VARCHAR(1024) NULL,
  `HumanName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Commentary_ID`),
  CONSTRAINT `fk_Commentary_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentary_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Commentary_User1_idx` ON `mydb`.`Commentary` (`User_ID` ASC);

CREATE INDEX `fk_Commentary_Object1_idx` ON `mydb`.`Commentary` (`Object_ID` ASC);

CREATE UNIQUE INDEX `Commentary_ID_UNIQUE` ON `mydb`.`Commentary` (`Commentary_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Object_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Object_User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Object_User` (
  `User_ID` INT NOT NULL,
  `Object_ID` INT NOT NULL,
  CONSTRAINT `fk_Object_User_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Object_User_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Object_User_Object1_idx` ON `mydb`.`Object_User` (`Object_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Operation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Operation` (
  `Operation_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`Operation_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Operation_ID_UNIQUE` ON `mydb`.`Operation` (`Operation_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`OperationField`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OperationField` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OperationField` (
  `OperationField_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Operation_ID` INT NOT NULL,
  PRIMARY KEY (`OperationField_ID`),
  CONSTRAINT `fk_OperationField_Operation1`
    FOREIGN KEY (`Operation_ID`)
    REFERENCES `mydb`.`Operation` (`Operation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_OperationField_Operation1_idx` ON `mydb`.`OperationField` (`Operation_ID` ASC);

CREATE UNIQUE INDEX `OperationField_ID_UNIQUE` ON `mydb`.`OperationField` (`OperationField_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Log` (
  `Log_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Object_ID` INT NOT NULL,
  `Operation_ID` INT NOT NULL,
  `CreationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `HumanName` VARCHAR(255) NULL,
  `ObjectName` VARCHAR(255) NULL,
  PRIMARY KEY (`Log_ID`),
  CONSTRAINT `fk_Log_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Log_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Log_Operation1`
    FOREIGN KEY (`Operation_ID`)
    REFERENCES `mydb`.`Operation` (`Operation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Log_User1_idx` ON `mydb`.`Log` (`User_ID` ASC);

CREATE INDEX `fk_Log_Object1_idx` ON `mydb`.`Log` (`Object_ID` ASC);

CREATE INDEX `fk_Log_Operation1_idx` ON `mydb`.`Log` (`Operation_ID` ASC);

CREATE UNIQUE INDEX `Log_ID_UNIQUE` ON `mydb`.`Log` (`Log_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`State` ;

CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `State_ID` INT NOT NULL AUTO_INCREMENT,
  `Object_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`State_ID`),
  CONSTRAINT `fk_State_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_State_Object1_idx` ON `mydb`.`State` (`Object_ID` ASC);

CREATE UNIQUE INDEX `State_ID_UNIQUE` ON `mydb`.`State` (`State_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `Task_ID` INT NOT NULL AUTO_INCREMENT,
  `Object_ID` INT NOT NULL,
  `State_ID` INT NOT NULL,
  `Title` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  `Progress` VARCHAR(255) NULL,
  `ConclusionDate` DATE NULL,
  PRIMARY KEY (`Task_ID`, `Object_ID`),
  CONSTRAINT `fk_Task_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_State1`
    FOREIGN KEY (`State_ID`)
    REFERENCES `mydb`.`State` (`State_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Task_Object1_idx` ON `mydb`.`Task` (`Object_ID` ASC);

CREATE INDEX `fk_Task_State1_idx` ON `mydb`.`Task` (`State_ID` ASC);

CREATE UNIQUE INDEX `Task_ID_UNIQUE` ON `mydb`.`Task` (`Task_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`LogField`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LogField` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LogField` (
  `LogField_ID` INT NOT NULL AUTO_INCREMENT,
  `Log_ID` INT NOT NULL,
  `OperationField_ID` INT NOT NULL,
  `Content` VARCHAR(255) NULL,
  PRIMARY KEY (`LogField_ID`),
  CONSTRAINT `fk_LogField_Log1`
    FOREIGN KEY (`Log_ID`)
    REFERENCES `mydb`.`Log` (`Log_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LogField_OperationField1`
    FOREIGN KEY (`OperationField_ID`)
    REFERENCES `mydb`.`OperationField` (`OperationField_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_LogField_Log1_idx` ON `mydb`.`LogField` (`Log_ID` ASC);

CREATE INDEX `fk_LogField_OperationField1_idx` ON `mydb`.`LogField` (`OperationField_ID` ASC);

CREATE UNIQUE INDEX `LogField_ID_UNIQUE` ON `mydb`.`LogField` (`LogField_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `Client_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`Client_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Client_ID_UNIQUE` ON `mydb`.`Client` (`Client_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Opportunity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Opportunity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Opportunity` (
  `Object_ID` INT NOT NULL,
  `State_ID` INT NOT NULL,
  `Client_ID` INT NOT NULL,
  `Title` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`Object_ID`),
  CONSTRAINT `fk_Opportunity_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Opportunity_State1`
    FOREIGN KEY (`State_ID`)
    REFERENCES `mydb`.`State` (`State_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Opportunity_Client1`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `mydb`.`Client` (`Client_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = tis620;

CREATE INDEX `fk_Opportunity_State1_idx` ON `mydb`.`Opportunity` (`State_ID` ASC);

CREATE INDEX `fk_Opportunity_Client1_idx` ON `mydb`.`Opportunity` (`Client_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Solution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Solution` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Solution` (
  `Object_ID` INT NOT NULL,
  `Opportunity_Object_ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `YearsOfExperience` INT NULL,
  `AvailableDate` DATE NULL,
  PRIMARY KEY (`Object_ID`),
  CONSTRAINT `fk_Solution_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solution_Opportunity1`
    FOREIGN KEY (`Opportunity_Object_ID`)
    REFERENCES `mydb`.`Opportunity` (`Object_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Solution_Opportunity1_idx` ON `mydb`.`Solution` (`Opportunity_Object_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Attachment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Attachment` (
  `Attachment_ID` INT NOT NULL AUTO_INCREMENT,
  `Object_ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  `Content` VARCHAR(255) NULL,
  PRIMARY KEY (`Attachment_ID`),
  CONSTRAINT `fk_Attachment_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `mydb`.`Object` (`Object_ID`)
    ON DELETE NO ACTIclientUser_IDON
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Attachment_Object1_idx` ON `mydb`.`Attachment` (`Object_ID` ASC);

CREATE UNIQUE INDEX `Attachment_ID_UNIQUE` ON `mydb`.`Attachment` (`Attachment_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
